version: "3.9"
services:
  app:
    build: .
    env_file:
      - .env.docker
    ports:
      - "7000:7000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env.docker
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
